# Site wide configuration

title: Tyler Abbot
description: My personal website
logo: pipo_logo.png # 120x120 px default image used for Twitter summary card
teaser: paper_stack.jpg # 400x250 px default teaser image used in image archive grid
locale: "en_US"
url: 'https://tyler-abbot.github.io'
icon: mandelbrot4.png #The image to be used for facebook posts. Always the same

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Tyler Abbot
  email: tyler.abbot@sciencespo.fr
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:  Nerd extraordinaire.
  avatar: bio-photo2.jpg # 160x160 px image for author byline
disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
